### ISSUE TITLE
[Bug]: Creating event with `id` or `phase` causes problems

### ISSUE THREAD

**Issue by markjaquith** [hirethunk/verbs#31]
### What happened?

Verbs stores the user's event data mingled with internal Verbs data. Thus:

1. You cannot create an event with a `phase` property. (`Type of App\Events\BrokeVerbs::$phase must be Thunk\Verbs\Lifecycle\Phase (as in class Thunk\Verbs\Event)`)
2. If you create an `id` property (of type `int`), no error will be thrown, but Verbs will nuke it and overwrite it with that row's `id` snowflake.

The `phase` one isn't too bad. You get an error, and anyone encountering it will likely realize they need to rename their `phase` in that event.

The `id` one is kinda nasty. It's highly likely someone will try this, and it just silently overwrites their data.

Some questions:

1. Could these internal fields be prefixed with an underscore to reduce the chance of accidental collision?
2. Is it necessary to store `id` in both the `id` column of an event and also in the JSON `data` column?
3. Is it necessary to store `phase` in the database at all?

### How to reproduce the bug

```php
<?php

namespace App\Events;

use Thunk\Verbs\Event;

class BrokeVerbsPhase extends Event {
	public function __construct(public string $phase) {
	}
	public function handle() {
	}
}
```

```php
<?php

namespace App\Events;

use Thunk\Verbs\Event;

class BrokeVerbsId extends Event {
	public function __construct(public int $id) {
	}
	public function handle() {
	}
}
```

Then just fire those events.

### Package Version

0.0.6

### PHP Version

8.1.26

### Laravel Version

10.10

### Which operating systems does with happen with?

macOS

**Comment by inxilpro** [comment]
This is a great point. Been thinking about this as well. I think you're right… it'd be nice if they don't have to live on the event object at all.

**Comment by inxilpro** [comment]
The metadata PR may also help with this…

**Comment by inxilpro** [comment]
So I removed `phase` from events, because I think you're 100% right there. I do think that we need all events to have an `$id` but I've updated things so that IDs are only set if they weren't provided, which means that if you define a public `$id` property on your event and fill it with something yourself, Verbs will honor that. Does that feel like a good resolution?

**Comment by markjaquith** [comment]
I think that if they are passing in an `id` they will be expecting it to be **their** `id`, not the event's `id`, and it could lead to events with conflicting event `id`s (which presumably would prevent the event from being inserted).

**Comment by inxilpro** [comment]
> I think that if they are passing in an `id` they will be expecting it to be **their** `id`, not the event's `id`, and it could lead to events with conflicting event `id`s (which presumably would prevent the event from being inserted).

I guess… why would you set an `$id` property on an event if it's not the event's ID?

**Comment by skylerkatz** [comment]
> I guess… why would you set an `$id` property on an event if it's not the event's ID?

Let's say I have a `ArticleCreated` event. The `ArticleState` id needs to reference some id. In my mind, it would be nice to be able to have that be `id` rather than `article_id`. That way, in my handle method I could just do `Article::create(['id' => $this->id]);` rather than `$this->article_id`.

Later, in an `ArticleUpdated` event I still want to pass in `id` rather than `article_id`.

Right now, none of that is really possible.

**Comment by skylerkatz** [comment]
Seems like the existing `id` that verbs is using should be called `verb_id` or `verbs_event_id`
